"channel: bluebubbles":
  - "extensions/bluebubbles/**"
  - "docs/channels/bluebubbles.md"
"channel: discord":
  - "src/discord/**"
  - "extensions/discord/**"
  - "docs/channels/discord.md"
"channel: googlechat":
  - "extensions/googlechat/**"
  - "docs/channels/googlechat.md"
"channel: imessage":
  - "src/imessage/**"
  - "extensions/imessage/**"
  - "docs/channels/imessage.md"
"channel: line":
  - "extensions/line/**"
"channel: matrix":
  - "extensions/matrix/**"
  - "docs/channels/matrix.md"
"channel: mattermost":
  - "extensions/mattermost/**"
  - "docs/channels/mattermost.md"
"channel: msteams":
  - "extensions/msteams/**"
  - "docs/channels/msteams.md"
"channel: nextcloud-talk":
  - "extensions/nextcloud-talk/**"
  - "docs/channels/nextcloud-talk.md"
"channel: nostr":
  - "extensions/nostr/**"
  - "docs/channels/nostr.md"
"channel: signal":
  - "src/signal/**"
  - "extensions/signal/**"
  - "docs/channels/signal.md"
"channel: slack":
  - "src/slack/**"
  - "extensions/slack/**"
  - "docs/channels/slack.md"
"channel: telegram":
  - "src/telegram/**"
  - "extensions/telegram/**"
  - "docs/channels/telegram.md"
"channel: tlon":
  - "extensions/tlon/**"
  - "docs/channels/tlon.md"
"channel: voice-call":
  - "extensions/voice-call/**"
"channel: whatsapp-web":
  - "src/web/**"
  - "extensions/whatsapp/**"
  - "docs/channels/whatsapp.md"
"channel: zalo":
  - "extensions/zalo/**"
  - "docs/channels/zalo.md"
"channel: zalouser":
  - "extensions/zalouser/**"
  - "docs/channels/zalouser.md"

"app: android":
  - "apps/android/**"
  - "docs/platforms/android.md"
"app: ios":
  - "apps/ios/**"
  - "docs/platforms/ios.md"
"app: macos":
  - "apps/macos/**"
  - "docs/platforms/macos.md"
  - "docs/platforms/mac/**"
"app: web-ui":
  - "ui/**"
  - "src/gateway/control-ui.ts"
  - "src/gateway/control-ui-shared.ts"
  - "src/infra/control-ui-assets.ts"

"cli":
  - "src/cli/**"
  - "src/commands/**"
  - "src/tui/**"

"gateway":
  - "src/gateway/**"
  - "src/daemon/**"
  - "docs/gateway/**"

"docs":
  - "docs/**"
  - "docs.acp.md"

"extensions: copilot-proxy":
  - "extensions/copilot-proxy/**"
"extensions: diagnostics-otel":
  - "extensions/diagnostics-otel/**"
"extensions: google-antigravity-auth":
  - "extensions/google-antigravity-auth/**"
"extensions: google-gemini-cli-auth":
  - "extensions/google-gemini-cli-auth/**"
"extensions: llm-task":
  - "extensions/llm-task/**"
"extensions: lobster":
  - "extensions/lobster/**"
"extensions: memory-core":
  - "extensions/memory-core/**"
"extensions: memory-lancedb":
  - "extensions/memory-lancedb/**"
"extensions: open-prose":
  - "extensions/open-prose/**"
"extensions: qwen-portal-auth":
  - "extensions/qwen-portal-auth/**"
